### ISSUE TITLE
Cannot seem to get NSFW images from boorus even with filter change

### ISSUE THREAD

**Issue by ibigfire** [Jintaku/Jintaku-Cogs-V3#2] opened 2019-02-04 03:18 UTC
Upon removal of the default "rating:s" filter and changing my server filters to be `rating:explicit,rating:questionable` inputting both `[p]booru nude` and `[p]booru rating:explicit nude` seem to return random sfw images instead of the requested nsfw images with the requested tag.

It is entirely possible I'm at fault here and it is user error, but I'm not sure what I could be doing wrong.

Also in the code for booru.py "questionable" is misspelled as "questionnable" throughout, but that's not a big deal.

**Comment by lionirdeadman** [comment] 2019-02-08 19:28
That's strange, if you've removed the rating:s filter that's on by default, it should work.. That said, the filter system in this version of booru was kind of really bad, I have a new version in the work with a bunch of improvements and that should hopefully fix this.

Really sorry for not seeing this earlier! :disappointed:

**Comment by lionirdeadman** [comment] 2019-02-09 00:15
The new version is out, it should work. Update :smirk:

**Comment by lionirdeadman** [comment] 2019-02-13 23:44
I will close this issue because I've not been able to reproduce it. Feel free to reopen.

**Closed as completed by lionirdeadman** 2019-02-13 23:44 UTC

**Comment by ibigfire** [comment] 2019-02-17 04:42
It seems to work now.  Thank you for fixing it, and no worries on the delayed response!  We all have lives to attend to it's all good.  Even with filters removed it will only retrieve explicit images when specifically called for them via tags, but I assume that's intended behaviour.  I actually want to reverse it so that by default it will retrieve explicit and questionable rated images and only retrieve safe ones if specifically asked for, but I suppose I can try to dig into the code to make it work that way.  Thank you very much!

**Comment by lionirdeadman** [comment] 2019-02-18 02:52
Actually, by default it now search for *no ratings in particular* if in a NSFW channel and will force safe in SFW channels, as for forcing tags, it's no longer a thing since I changed the filtering system to be local instead of sending that information to the image boards, you make an alias for it, I believe. Please feel free to find me on Discord if you have any other feedback or need support in any way which you don't is worth opening an issue for.
